name: wowsy
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  bloc: ^0.8.0
  flutter_bloc: ^0.5.0
  meta: ^1.1.6
  equatable: ^0.1.6
  simple_autocomplete_formfield: ^0.2.3
  datetime_picker_formfield: ^0.1.7
  shared_preferences: ^0.4.2
  numberpicker: ^0.1.7
  cupertino_icons: ^0.1.2
  advanced_share: ^0.1.0
  font_awesome_flutter: ^8.4.0
  flutter_datetime_picker: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
     - family: Quicksand
       fonts:
          - asset: fonts/Quicksand-Bold.ttf
          - asset: fonts/Quicksand-Light.ttf
          - asset: fonts/Quicksand-Medium.ttf
          - asset: fonts/Quicksand-Regular.ttf

